version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atd_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:7773 --workers 3 --timeout 180"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  
      - ./db.sqlite3:/app/db.sqlite3      
    ports:
      - "7773:7773"
    env_file:
      - .env
    networks:
      - django_net
    restart: unless-stopped

volumes:
  static_volume:

networks:
  django_net:
    driver: bridge
